# Generated by Django 5.0.9 on 2026-07-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("invoice", "Invoice"),
                    ("sales_payment", "Sales payment"),
                    ("goods_receipt", "Goods receipt"),
                    ("purchase_payment", "Purchase payment"),
                    ("pos_sale", "POS sale"),
                    ("pos_refund", "POS refund"),
                    ("expense", "Expense"),
                    ("closing", "Period closing"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
