# Generated by Django 5.0.9 on 2026-07-09 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="e.g. product_sku, invoice, purchase_order",
                        max_length=50,
                    ),
                ),
                ("prefix", models.CharField(blank=True, max_length=20)),
                ("next_number", models.PositiveIntegerField(default=1)),
                ("padding", models.PositiveSmallIntegerField(default=5)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "key")},
            },
        ),
    ]
