# Generated by Django 5.0.9 on 2026-07-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0003_purchaserequest_purchaseorder_purchase_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="batch_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
