# Generated by Django 5.0.9 on 2026-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0004_goodsreceiptitem_batch_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptitem",
            name="serial_numbers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
