# Generated by Django 5.0.9 on 2026-07-10 20:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("suppliers", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.company",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_account",
                        to="customers.customer",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_account",
                        to="suppliers.supplier",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="portalaccount",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("customer__isnull", False), ("supplier__isnull", True)),
                    models.Q(("customer__isnull", True), ("supplier__isnull", False)),
                    _connector="OR",
                ),
                name="portal_account_exactly_one_of_customer_or_supplier",
            ),
        ),
    ]
