# Generated by Django 5.0.9 on 2026-07-10 22:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderitem",
            name="quantity_invoiced",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=14
            ),
        ),
    ]
